version: '3'
services:
  postgres:
    image: "postgres:9.5.16-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tiny_task
      - POSTGRES_USER=tiny_task
      - POSTGRES_PASSWORD=demo123
      - PGDATA=/tmp
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
