spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiny_task
    username: tiny_task
    password: demo123
  flyway:
    url: jdbc:postgresql://localhost:5432/tiny_task
    user: tiny_task
    password: demo123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    com.coyoapp.tinytask: DEBUG
