spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiny_task
    username: tiny_task
    password: demo123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate


    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true:spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


logging:
  level:
    com.coyoapp.tinytask: DEBUG

